### ISSUE TITLE
Create an informative README.md

### ISSUE THREAD

**Issue by Anuj-Kumar-Sharma** [Anuj-Kumar-Sharma/DS-Algo#3]
Readme.md is an important file for any project hosted on a version control system. It helps the developers know more about the project, the setup process, and how to get started with the project.

We require to make a good and informative README for our DS-Algo project. 
Don't know how to get started? Go through this article [https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project](https://bulldogjob.com/news/449-how-to-write-a-good-readme-for-your-github-project)

**Comment by Shaikh-Nabeel** [comment]
Sir, Is it important to keep length short for content in Readme files?

**Comment by Anuj-Kumar-Sharma** [comment]
@Shaikh-Nabeel Good job with the updated readme.md. Please always make sure that it always remains valid and updated.
