### ISSUE TITLE
Looking to contribute at Apni Kaksha

### ISSUE THREAD

**Issue by suyash0103** [Anuj-Kumar-Sharma/DS-Algo#30]
Hi Anuj, is there anything I can contribute in your repository? I would to like to help you in your mission to educate students and prepare them for placements. Please view my GitHub profile, and if you find me eligible, let me know how I can contribute to this repository.

**Comment by Anuj-Kumar-Sharma** [comment]
Yes, you are free to contribute. but It's not an "Issue" 😄 right?
